config/routes.rb
  Rails.application.routes.draw do
  root 'welcome#index'
  get '/welcome/edit', :to => 'welcome#edit'
  post '/search', :to => 'welcome#search'

  get 'addresource', :to => 'media#addresource'

  get 'register' => 'players#new, as: :register'
  get 'logout' => 'sessions#destroy, as: :logout'

  resources :teams
  post 'teamss/search', :to => 'teams#search'
  resources :media
  get 'media/:id', :to => 'teams#media'
  resources :sports, only: [:create, :new, :show, :destroy]
  resources :positions, only: [:create, :new, :show, :destroy]
  resources :medium
  resources :players
  post 'players/search', :to => 'players#search'
  post 'players/:id/email', :to => 'players#email', as: :email_player

  get '/login', :to => 'sessions#new', as: :login
  get 'auth/:provider', :to => 'sessions#new', as: :oauth_login
  get '/auth/:provider/callback', to: 'players#create'
  get '/auth/failure', to: 'sessions#failure'
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_secure_password
  acts_as_mappable :lat_column_name => :latitude,
                   :lng_column_name => :longitude

  before_save :has_lat_long

  validates :username, presence: true

  has_many :player_sports
  has_many :player_positions
  has_many :player_teams
  has_many :positions, through: :player_positions
  has_many :sports, through: :player_sports
  has_many :teams, through: :player_teams
  has_many :media, as: :showable


  def self.validate_via_provider(auth)
    @player = Player.find_by(provider: auth[:provider], uid: auth[:uid])
    @player = Player.new(provider: auth[:provider], uid: auth[:uid]) unless @player
    @player.username = auth[:info][:name]
    if @player.new_record?
      @player.password = SecureRandom.uuid()
      @player.phone = '122345689'
      @player.save
    end
      @player
  end

  def has_positions?
    self.positions.any?
  end

  def has_media?
    self.media.any?
  end

  def parse_address
    address = self.address
    city = self.city
    state = self.state
    zip = self.zip
    address = "#{address} #{city} #{state} #{zip}"
  end

  def lat_long
    # OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE
    if self.latitude == nil && self.longitude == nil
      addr = URI.escape(parse_address)
      res = HTTParty.get("https://maps.googleapis.com/maps/api/geocode/json?address=#{addr}&key=AIzaSyC7dmZEFn1tJOy7zeVH2Hce3tF8U0_MnIg")
      lat =  res["results"][0]["geometry"]["location"]["lat"]
      lng =  res["results"][0]["geometry"]["location"]["lng"]
      self.update(latitude: lat, longitude: lng)
    end
  end

  def has_lat_long
    if self.address && self.latitude == nil && self.longitude == nil
      lat_long
    elsif self.address == nil
    end
  end

def map_string
  "&markers=color:red%7Clabel:" + "#{self.username.first}" +"%7C" + "#{self.latitude.to_f.to_s}," + "#{self.longitude.to_f.to_s}"
end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
    @players = Player.all
  end

  def new
    @sports = Sport.all
    @player = Player.new
    if @player.city == nil
      render :status => 404
    end
  end

  def create
    auth = request.env['omniauth.auth']
    @player = Player.validate_via_provider(auth)
    @sports = Sport.pluck(:name)
    if @player
      session[:player_id] = @player.id
      if @player.has_positions?
        redirect_to player_path(@player)
      else
        render :new
      end
    else
      redirect_to root_path
    end
  end

  def show
    @player = Player.find(params[:id])
  end

  def email
    @player = Player.find(params[:id])
    PlayerMailer.player_email(@player, current_player).deliver_now
    flash[:notice] = "Your email has been sent!"
    redirect_to root_path
  end

  def edit
    @player = Player.find(params[:id])
    @sports = Sport.pluck(:name)
  end

  def update
    @player = Player.find(params[:id])

    if @player.save
      if params.has_key?("sport_types")
        @player.sports = []
        @sports = params[:sport_types]
        @sports.each do |sport|
          @player.sports << Sport.find_or_create_by(name: sport.strip)
        end
      else
        @player.sports.delete_all
      end

      @positions = params[:player][:positions].split(",")
      if @positions.any?
        @positions.each do |position|
          unless @player.positions.map(&:name).include?(position)
            @player.positions << Position.find_or_create_by(name: position.strip)
          end
        end
      end

        @player.update_attributes(player_params)
        if @player.email
          puts "Sending email"
          PlayerMailer.welcome_email(@player).deliver_now
        end
        @player.lat_long
        redirect_to player_path(@player)
      else
        render :edit
      end
    end


  def destroy
    @player = Player.find(params[:id])
    @player.destroy
    session[:player_id] = nil
    redirect_to root_path
  end

  def search
    if params["Sport"]
      sport_ids = params["Sport"].map {|e| e[0].to_i}
      sports = Sport.find(sport_ids)
      sports_with_athletes = sports.select {|sport| !sport.players.empty?}
      if sports_with_athletes.count > 1
        @athletes = sports_with_athletes.flat_map {|sport| sport.players}.uniq
      else
        @athletes = sports_with_athletes.map {|sport| sport.players}.flatten
      end
      @athletes_ids = @athletes.map {|athlete| athlete.id}
      @positions = Position.all
      render "players/_athletes-positions", layout: false
    elsif params["Position"]
      athletes_ids = params["athletes"].split(" ").map {|e| e.to_i}
      @original_athletes = Player.find(athletes_ids)
      position_ids = params["Position"].map {|e| e[0].to_i}
      positions = Position.find(position_ids)
      position_with_athletes = positions.select {|position| !position.players.empty?}
      if position_with_athletes.count > 1
        @athletes = position_with_athletes.flat_map {|position| position.players}.uniq
      else
        @athletes = position_with_athletes.map {|position| position.players}.flatten
      end
      @athletes = @original_athletes & @athletes
      @athletes_ids = @athletes.map {|athlete| athlete.id}
      render "users/_athletes-location", layout: false
    elsif params["Distance"]
      athletes_ids = params["athletes"].split(" ").map {|e| e.to_i}
      original_athletes = Player.find(athletes_ids)
      player_location = [current_player.latitude, current_player.longitude]
      distance = params["Distance"][0].to_i
      all_athletes_near = Player.within(distance, :origin => player_location)
      @athletes = original_athletes & all_athletes_near
      @map_string = "https://maps.googleapis.com/maps/api/staticmap?size=600x300&maptype=roadmap" + @athletes.map {|athlete| athlete.map_string}.join("") + "&key=AIzaSyDbL6SGxiaR5BjXdzLPJHxQyjIAhoBVz_o"
      render "players/_athletes-sorted", layout: false
    end
  end

  private

  def player_params
    player_params = params.require(:player).permit(:username, :email, :password_digest, :address, :city, :state, :zip, :phone, :info)
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_athlete-media.html.erb
<div class="add_resources">
  <select>
    <option value="youtube">YouTube</option>
    <option value="soundcloud">SoundCloud</option>
    <option value="image">Image</option>
  </select>
  <div><%= text_field :media, size: "300x1", placeholder: "Copy and paste here:" %></div>
</div>
  <button class="media">Add One</button>

app/views/players/_athletes-add-media.html.erb
 <select>
    <option value="youtube">YouTube</option>
    <option value="soundcloud">SoundCloud</option>
    <option value="image">Image</option>
  </select>
  <div><%= text_area :media, size: "60x1", placeholder: "Copy and paste here:" %></div>

app/views/players/_athletes-location.html.erb
<div id="athletes-location">
<% if !@athletes.empty? %>
  <% if logged_in? %>
    <div class="jumbotron text-center drop-shadow">
      <h1>Select a Distance:</h1>
      <div>
        <%= form_tag("players/search", method: "post") do %>
        <%= label_tag("Miles") %>
        <%= select("Distance", nil, ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], {:include_blank => true}) %>
        <%= hidden_field_tag :athletes, @athletes_ids %>
        <br>
        <%= submit_tag("Search", :class => "btn btn-primary btn-lg") %>
        <% end %>
      </div>
  </div>
  <% else %>
    <div class="alert alert-danger" role="alert">
      <h2 class="text-center">Sorry, you have to be logged-in to use our geo-search option. Here are your results based on sport and positions:</h2>
    </div>
  <% end %>

<div class="alert alert-success" role="alert">
  <h2 class="text-center"><%= @athletes.count  %> <%= @athletes.count > 1 ? "results:" : "result:" %></h2>
</div>

 <div class="row">
   <% @athletes.each do |athlete| %>
  <div class="col-sm-6 col-md-4">
  <div class="drop-shadow">
    <div class="thumbnail">
      <div class="caption">
        <h3 class="text-center"><%= athlete.username %></h3>
        <% if !athlete.postions.empty? %>
        <p class="text-center"><%= athlete.positions.first.name %>
           <% if !athlete.sports.empty? %> | <%= athlete.sports.first.name %>
        </p>
        <% end %>
        <% end %>
        <% if logged_in? %>
          <p class="text-center"><%= athlete.city %>, <%= athlete.state %> | Miles from me: <%= athlete.distance_from(Player.find(current_player.id), :units=>:miles).round() %></p>
          <p class="text-right"><a href="/users/<%= athlete.id %>" class="btn btn-primary" role="button">Profile</a></p>
        <% end %>
      </div>
    </div>
    </div>
  </div>
  <% end %>
</div>

<% else %>
<div class="alert alert-danger" role="alert">
  <h2 class="text-center">Sorry, there are no results that match that query.</h2>
</div>
<%= link_to "Home", root_path, :class => "btn btn-primary btn-lg" %>
<% end %>
</div>

app/views/players/_athletes-positions.html.erb
<div id="athlete-positions-search">
  <% if !@athletes.empty? %>
    <div class="jumbotron text-center">
      <h1>Select a position:</h1>
      <div>
        <%= form_tag("players/search", method: "post") do %>
          <% @positions.each do |position_obj| %>
          <div class="athlete-radio-button">
            <%= check_box_tag("[Position][#{position_obj.id}]", "#{position_obj.name}") %>
            <%= label_tag("#{position_obj.name}", nil, :class => "h2") %>
          </div>
          <%= hidden_field_tag :athletes, @athletes_ids %>
        <% end %>
        <br>
        <%= submit_tag("Search", :class => "btn btn-primary btn-lg") %>
        <% end %>
      </div>
    </div>

    <div class="alert alert-success" role="alert">
      <h2 class="text-center"><%= @athletes.count  %> <%= @athletes.count > 1 ? "results:" : "result:" %></h2>
    </div>

    <div class="row">
       <% @athletes.each do |athlete| %>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <div class="caption">
            <h3 class="text-center"><%= athlete.username %></h3>
            <% if !athlete.positions.empty? %>
               <p class="text-center"><%= athlete.positions.first.name %>
                <% if !athlete.sports.empty? %> | <%= athlete.sports.first.name %>
              </p>
            <% end %>
            <% end %>
            <% if logged_in? %>
             <p class="text-center"><%= athlete.city %>, <%= athlete.state %> | Miles from me: <%= athlete.distance_from(Player.find(current_player.id), :units=>:miles).round() %></p>
             <p class="text-right"><a href="/players/<%= athlete.id %>" class="btn btn-primary" role="button">Profile</a></p>
           <% end %>
         </div>
          </div>
        </div>
      </div>
    </div>

  <% else %>
    <div class="alert alert-danger" role="alert">
      <h2 class="text-center">Sorry, there are no results that match that query.</h2>
    </div>
    <%= link_to "Home", root_path, :class => "btn btn-primary btn-lg" %>
  <% end %>

</div>

app/views/players/_athletes-sport.html.erb
<div id="athlete-search-sport">
  <h4>Choose an Genre:</h4>
  <div>
    <%= form_tag("teams/search", method: "get") do %>
    <% @sports.uniq.each do |sport_obj| %>
    <%= radio_button_tag(:genre, "#{sport_obj.name}") %>
    <%= label_tag("#{sport_obj.name}") %>
    <% end %>
    <%= submit_tag("Search") %>
    <% end %>
  </div>

  <div>
    <h4>Athletes</h4>
    <ol>
      <% @athletes.each do |athlete| %>
      <li><%= athlete.username %></li>
      <% end %>
    </ol>
  </div>

</div>

app/views/players/_athletes.html.erb
<div id="athlete-search-sport">

<div class="jumbotron text-center">
  <h1>Select a Sport:</h1>
  <div>
    <%= form_tag("players/search", method: "post") do %>
    <% @sports.each do |sport_obj| %>
    <div class="athlete-radio-button">
    <%= check_box_tag("[Sport][#{sport_obj.id}]", "#{sport_obj.name}") %>
    <%= label_tag("#{sport_obj.name}", nil, :class => "h2") %>
    </div>
    <% end %>
    <%= hidden_field_tag :group, "Athletes" %>
    <br>
    <%= submit_tag("Search", :class => "btn btn-primary btn-lg") %>
    <% end %>
  </div>
</div>


<div class="alert alert-success" role="alert">
  <h2 class="text-center"><%= @athletes.count  %> <%= @athletes.count > 1 ? "results:" : "result:" %></h2>
</div>

<div class="row">
   <% @athletes.each do |athlete| %>
  <div class="col-sm-6 col-md-4">
  <div class="drop-shadow">
    <div class="thumbnail">
      <div class="caption">
        <h3 class="text-center"><%= athlete.username %></h3>
        <% if !athlete.positions.empty? %>
        <p class="text-center"><%= athlete.positions.first.name %>
           <% if !athlete.sports.empty? %> | <%= athlete.sports.first.name %>
        </p>
        <% end %>
        <% end %>
        <% if logged_in? %>
        <p class="text-center"><%= athlete.city %>, <%= athlete.state %> | Miles from me: <%= athlete.distance_from(Player.find(current_player.id), :units=>:miles).round() %></p>
        <p class="text-right"><a href="/players/<%= athlete.id %>" class="btn btn-primary" role="button">Profile</a></p>
        <% end %>
      </div>
    </div>
    </div>
  </div>
  <% end %>
</div>

</div>

app/views/players/_athletes_sorted.html.erb
<div id="athletes-location">
<% if !@athletes.empty? %>

<div class="col-md-6">

  <div class="alert alert-success" role="alert">
    <h2 class="text-center"><%= @athletes.count  %> <%= @athletes.count > 1 ? "results:" : "result:" %></h2>
  </div>

   <div class="row">
     <% @athletes.each do |athlete| %>
    <div class="col-sm-6 col-md-4">
    <div class="drop-shadow">
      <div class="thumbnail">
        <div class="caption">
          <h3 class="text-center"><%= athlete.username %></h3>
          <% if !athlete.positions.empty? %>
          <p class="text-center"><%= athlete.positions.first.name %>
             <% if !athlete.sports.empty? %> | <%= athlete.sports.first.name %>
          </p>
          <% end %>
          <% end %>
          <% if logged_in? %>
          <p class="text-center"><%= athlete.city %>, <%= athlete.state %> | Miles from me: <%= athlete.distance_from(Player.find(current_player.id), :units=>:miles).round() %></p>
          <p class="text-right"><a href="/players/<%= athlete.id %>" class="btn btn-primary" role="button">Profile</a></p>
          <% end %>
          </div>
      </div>
      </div>
    </div>
    <% end %>
  </div>
  </div>

<div class="col-md-6">
<h3 class="map-title">Map Results: (Marker uses first letter of name)</h3>
<img class="map-container" src="<%= @map_string  %>">
</div>

<% else %>
<div class="alert alert-danger" role="alert">
  <h2 class="text-center">Sorry, there are no results that match that query.</h2>
</div>
<%= link_to "Home", root_path, :class => "btn btn-primary btn-lg" %>
<% end %>
</div>

app/views/players/athletes_sorted.html.erb
<div id="athletes-sorted">
<% if !@athletes.empty? %>

<div class="alert alert-success" role="alert">
  <h2 class="text-center"><%= @athletes.count  %> <%= @athletes.count > 1 ? "results:" : "result:" %></h2>
</div>

<div class="row">
 <% @athletes.each do |athlete| %>
 <div class="col-sm-6 col-md-4">
  <div class="thumbnail">
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYeMmqgj1FO8TbWrQoyo33lLB23fY0xpU6i-yWB4qdjf1mtYTrteryRQ" alt="..." class="pull-left">
    <div class="caption">
      <h3 class="text-center"><%= athlete.username %></h3>
      <p class="text-center"><%= athlete.positions.first.name %></p>
      <% if !athlete.sports.empty? %>
      <p class="text-center"><%= athlete.sports.first.name %></p>
      <% end %>
      <p class="text-right"><a href="/players/<%= athlete.id %>" class="btn btn-primary" role="button">Profile</a> </p>
    </div>
  </div>
</div>
<% end %>
</div>
<% else %>
<div class="alert alert-danger" role="alert">
  <h2 class="text-center">Sorry, there are no results that match that query.</h2>
</div>
<%= link_to "Home", root_path, :class => "btn btn-primary btn-lg" %>
<% end %>
</div>

app/views/players/edit.html.erb
<div class="container">
<h2>Update My Profile</h2>

<h2>Update your information below:</h2>
<%= form_for @player, url: player_path(@player), method: :put do |f| %>

  <% if @errors %>
    <% @player.errors.full_messages.each do |error| %>
      <h2 class=""><%= error %></h2><br>
    <% end %>
  <% end %>

  <p><%= f.label :username %></p>
  <p><%= f.text_field :username %></p>

  <% @player.positions.each do |position| %>
     <p>
       <%= position.name.capitalize %>
       <%= link_to "Delete",  position_path(position), method: :delete %>
     </p>
   <% end %>
  <p><%= f.label "Enter new positions separated by a comma." %>:</p>
  <p><%= f.text_field :positions, :value => "" %></p>

  <p><%= f.label :sports %></p>
    <% @sports.each do |sport| %>
        <p>
          <% if @player.sports.pluck(:name).include?(sport) %>
            <%= check_box_tag 'sport_types[]', sport, true %>
            <%= sport %>
          <% else %>
            <%= check_box_tag 'sport_types[]', sport %>
            <%= sport %>
          <% end %>
        </p>
    <% end %>

  <p><%= f.label :email %></p>
  <p><%= f.text_field :email %></p>

  <p><%= f.label :phone %></p>
  <p><%= f.text_field :phone %></p>

  <p><%= f.label :info %></p>
  <p><%= f.text_area :info %></p>


  <%= f.submit "Update", class: "button" %>
<% end %>
</div>

app/views/players/index.html.erb
<div class="container">
  <h1 align="center">List of Athletes</h1>
  <table border="1" style="width:85%" align="center">
    <tr>
    <th style="background-color:grey">Name: </th>
    <th style="background-color:grey">Info: </th>
    <th style="background-color:grey">Address: </th>
    <th style="background-color:grey">Phone: </th>
    <th style="background-color:grey">Email: </th>
    <th style="background-color:grey">Sports: </th>
    <th style="background-color:grey">Positions: </th>
    </tr>
    <% @players.each do |player| %>
    <tr>
      <td><%= player.username %></td>
      <td><%= player.info %></td>
      <td><%= player.address %>, <%= player.city %>, <%= player.state %> <%= player.zip %></td>
      <td><%= player.phone %></td>
      <td><%= player.email %></td>
        <td>
        <% player.sports.each do |sport| %>
        <%= sport.name %>
        <% end %>
        </td>
        <td>
        <% player.positions.each do |position| %>
        <%= position.name %>
        <% end %>
        </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/players/new.html.erb
<span>Thanks For Joining TeamMatch!</span>
<span>We Need To Verify Some Of Your Information</span>

<%= form_for @player do |f| %>

<% if @errors %>
    <% @player.errors.full_messages.each do |error| %>
      <h2 class=""><%= error %></h2><br>
    <% end %>
  <% end %>

  <p><%= f.label :username %></p>
  <p><%= f.text_field :username %></p>

  <h4>Please enter positions separated by a comma.</h4>
  <p><%= f.label :positions %></p>
  <p><%= f.text_field :positions, :value => "" %></p>

  <p><%= f.label :sports %></p>
   <% if @sports.any? %>
    <% @sports.each do |sport| %>
        <p>
          <%= check_box_tag 'sport_types[]', sport %>
          <%= sport %>
        </p>
    <% end %>
   <% end %>

  <p><%= f.label :email %></p>
  <p><%= f.text_field :email %></p>

  <p><%= f.label :address %></p>
  <p><%= f.text_field :address %></p>

  <p><%= f.label :city %></p>
  <p><%= f.text_field :city %></p>

  <p><%= f.label :state %></p>
  <p><%= f.text_field :state %></p>

  <p><%= f.label :zip %></p>
  <p><%= f.text_field :zip %></p>

  <p><%= f.label :phone %></p>
  <p><%= f.text_field :phone %></p>

  <p><%= f.label :info %></p>
  <p><%= f.text_area :info %></p>


  <%= f.submit "Verify", class: "button" %>
<% end %>
</div>

app/views/players/show.html.erb
<div class="jumbotron">
   <h2 class="player-profile"><%= @player.username %></h2>
 </div>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      <h3 class="player-profile">Positions</h3>
      <% @player.positions.each do |position| %>
      <p class="player-data"><%= position.name %></p>
      <% end %>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="btn-group" role="group">
        <% if logged_in? %>
          <%= button_to "Send Email", email_player_path(@player), class: "btn btn-lg" %>
          <% if current_player.id == @player.id %>
            <%= button_to "Edit Profile", edit_player_path(current_player), method: :get, class: "btn btn-lg" %>
            <%= button_to "Delete Profile", player_path, :confirm => 'Are you sure?',method: :delete, class: "btn btn-lg" %>
          <% end %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      <h3 class="player-profile">Sports</h3>
      <% @player.sports.each do |sport| %>
      <p class="player-data"><%= sport.name %></p>
      <% end %>
    </div>
    <div class "row">
      <div class="col-md-6">
        <% if logged_in? %>
          <% if current_player.id == @player.id %>
            <%= form_tag new_medium_path, method: "get" do %>
              <%= hidden_field_tag :player_id, @player.id %>
              <%= submit_tag("Add Media", class: "btn btn-lg") %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <h3 class="player-profile">Teams</h3>
      <% @player.teams.each do |team| %>
      <p class="player-data"><%= team.team_name %></p>
      <% end %>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      <h3 class="player-profile">Info</h3>
      <p class="player-data"><%= @player.info %></p>
    </div>
  </div>
</div>

<% if @player.has_media? %>
      <% @player.media.each do |resource| %>
          <% if resource.media_type == "image" %>
            <div class="image">
              <img src="<%= resource.link %>">
              <p> <%= resource.content %></p>
              <%= button_to "Delete This", media_path(resource), method: :delete, class: "btn btn-default" %>
            </div>
          <% end %>
          <% if resource.media_type == "youtube" %>
          <div class="youtube">
            <iframe width="600", height="495", src="<%= youtube_embed_link resource %>" , frameborder="0", allowfullscreen></iframe>
            <p class="media-resource-description"> <%= resource.content %></p>
            <%= button_to "Delete This", media_path(resource), method: :delete, class: "btn btn-default" %>
          </div>
          <% end %>
          <% if resource.media_type == "soundcloud" %>
          <div class="soundcloud">
            <div><%= link_to 'track', resource.link %></div>
            <p><%= resource.content %></p>
            <%= button_to "Delete This", media_path(resource), method: :delete, class: "btn btn-default" %>
          </div>
          <% end %>
        <% end %>
      <% end %>