config/routes.rb
  Rails.application.routes.draw do
  root 'welcome#index'
  get '/welcome/edit', :to => 'welcome#edit'
  post '/search', :to => 'welcome#search'

  get 'addresource', :to => 'media#addresource'

  get 'register' => 'players#new, as: :register'
  get 'logout' => 'sessions#destroy, as: :logout'

  resources :teams
  post 'teamss/search', :to => 'teams#search'
  resources :media
  get 'media/:id', :to => 'teams#media'
  resources :sports, only: [:create, :new, :show, :destroy]
  resources :positions, only: [:create, :new, :show, :destroy]
  resources :medium
  resources :players
  post 'players/search', :to => 'players#search'
  post 'players/:id/email', :to => 'players#email', as: :email_player

  get '/login', :to => 'sessions#new', as: :login
  get 'auth/:provider', :to => 'sessions#new', as: :oauth_login
  get '/auth/:provider/callback', to: 'players#create'
  get '/auth/failure', to: 'sessions#failure'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teammatch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="google-site-verification" content="esmpi_ieQ9F4MMAcS2dSZRhTL4402wurmudbaX05Jug" />
  <link href='https://fonts.googleapis.com/css?family=Josefin+Slab:300' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Playfair+Display:700' rel='stylesheet' type='text/css'>

</head>

<body>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
      <div class="navbar-header">
        <a class="site-title" href="/">TeamMatch</a>
      </div>
      <div class="navbar-buttons">
      <% if logged_in? %>
      <div id="logged-in-btns">
        <%= link_to "Log Out",  logout_path, :class => "navbar-text navbar-right link-nav" %>
        <%= link_to "#{current_player.username}", player_path(current_player), :class => "navbar-text navbar-right link-nav" %>
        <%= link_to 'Create a Team', new_team_path, :class => "navbar-text navbar-right link-nav" %>
      </div>
      <% else %>
      <div id="logged-out-btns">
        <%= link_to 'Google', oauth_login_path(:google_oauth2), :class => "navbar-text navbar-right link-nav" %>
        <%= link_to 'Twitter', oauth_login_path(:twitter), :class => "navbar-text navbar-right link-nav" %>
        <%= link_to 'Soundcloud', oauth_login_path(:soundcloud), :class => "navbar-text navbar-right link-nav" %>
      </div>
      <% end %>
    </div>
   </div>
  </div>

</nav>


<% if flash[:error] %>
  <div class='alert alert-error' role="alert">
    <h2 class="text-center">
     <%= flash[:error]%>
    </h2>
  </div>
<% end %>

<% if flash[:notice] %>
<div class='alert alert-success' role="alert">
  <h2 class="text-center">
    <%= flash[:notice]%>
  </h2>
</div>
<% end %>

<%= yield %>

</body>
</html>